#!/bin/sh
# shrink to a target width

# default prefix
VIPSHOME=${VIPSHOME-/root/parsec-3.0/pkgs/apps/vips/inst/amd64-linux.gcc-hooks}

name=$0
bname=`basename $0`

if [ $# != 3 ]; then
	echo "${bname}: usage: $bname <in> <out> <target width>"
	exit 1
fi

inwidth=`$VIPSHOME/bin/vips im_header_int Xsize $1`
factor=`(echo scale=10; echo $inwidth / $3) | bc`

$VIPSHOME/bin/vips im_shrink $1 $2 $factor $factor
